apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ravenveles/backend:1a1221cdcab6f2ec95ade1ad3212154281ffc3cb
          imagePullPolicy: Always
          ports:
            - containerPort: 80