apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ravenveles/backend:39c36be2f19ef3ef8161c3ced441e4662228390d
          imagePullPolicy: Always
          ports:
            - containerPort: 80