apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ravenveles/frontend:39c36be2f19ef3ef8161c3ced441e4662228390d
          imagePullPolicy: Always
          ports:
            - containerPort: 80